### PR TITLE
C++ code checks and metrics in TravisCI

### LINKED ISSUE #122: C++ code style & static code analysis in CI
It would be desirable to also have multiple checks for code quality, code style and static analysis of the code, independent of the compiler.

Possible code style checkers:
- [cpplint](https://github.com/google/styleguide/tree/gh-pages/cpplint) (Google)
- [KWStyle](https://github.com/Kitware/KWStyle) (KitWare)
- [vera++](https://bitbucket.org/verateam/vera/wiki/Introduction)
- ~[clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)~ #291

Possible code analysis tools:
- [OCLint](http://docs.oclint.org/en/stable/intro/tutorial.html)
- [Flint++](https://github.com/JossWhittle/FlintPlusPlus)
- ~[Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/)~ #291
- [clang-analyzer](https://clang-analyzer.llvm.org/scan-build.html) / `scan-build`
- ~[include_what_you_use](https://include-what-you-use.org/)~ #291
- [Cppcheck](http://cppcheck.sourceforge.net/)
- [Codacy](https://www.codacy.com/) (post-commit hook for Github integration)
- [Coverity](https://scan.coverity.com/)

Test / Code coverage:
- [cppcoveralls](https://github.com/eddyxu/cpp-coveralls)
- ~[kcov](https://github.com/SimonKagstrom/kcov)~ #291

### PR DESCRIPTION
**Pull request by anokfireball**
This adds a few new builds to the job matrix in travis:
 - C++ code style check through [clang-format](https://clang.llvm.org/docs/ClangFormat.html)
No custom style-configuration ```.clang-format``` that respects #134 is currently included. Thus, clang-format uses the default ```LLVM``` style and failure is expected.
**NOTE** Since creation of the custom ```.clang-format```, modification of the codebase to respect #134 and to pass this test is deferred to a later point in time, this build is marked as an *allowed failure*.
 - C++ static include analysis through [include_what_you_use](https://include-what-you-use.org/)
 **NOTE** Since modification of the codebase to pass this test is deferred to a later point in time, this build is marked as an *allowed failure*.
 - C++ static code analysis through [clang-tidy](http://clang.llvm.org/extra/clang-tidy/)
 All sensible checks that fit this project are currently applied and a few will-not-fix problems are silently excluded.
 **NOTE** Since modification of the codebase to pass this test is deferred to a later point in time, this build is marked as an *allowed failure*.
 - C++ code coverage analysis through [kcov](https://simonkagstrom.github.io/kcov/), pushed to [coveralls](https://coveralls.io/github/openPMD/openPMD-api)
  The overall coverage report is merged from the individual coverage results of all C++ API-tests in [```test/```](https://github.com/openPMD/openPMD-api/tree/0.3.1-alpha/test) and all C++ example binaries in [```examples/```](https://github.com/openPMD/openPMD-api/tree/0.3.1-alpha/examples).
  We will have to decide on a reasonable decrease in coverage percentage that will still pass. Currently, no percentage is specified, which means any percentage will pass.

Closes #122.

### CODE REVIEW

**Comment by ax3l** [comment]
Nice! Don't forget to remove the `[WIP]` and add a PR description when you are ready.

**Comment by anokfireball** [comment]
Will do. I've been tinkering with ```clang-tidy``` and ```include_what_you_use```, so they'll probably both get an entry in the ``` Static code analysis``` stage while I'm at it.

**Comment by ax3l** [comment]
Great! Be aware that CMake 3.9+ has excellent support for `clang-tidy` and `include_what_you_use` already :-)
https://blog.kitware.com/static-checks-with-cmake-cdash-iwyu-clang-tidy-lwyu-cpplint-and-cppcheck/

**Comment by anokfireball** [comment]
@ax3l Ready for review.

**Review by ax3l — APPROVED** [review]
Wonderful!

**Comment by ax3l** [comment]
@C0nsultant we could also add clang's address sanitizer to one of the builds. Checks memory leaks and address violations.

**Comment by ax3l** [comment]
@C0nsultant for `include-what-you-use`, we want to add [mappings](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md) for *examples*.

Otherwise, it will complain about things that user should include via the public header:
```
openPMD-api/examples/7_extended_write_serial.cpp should remove these lines:
- #include <openPMD/openPMD.hpp>  // lines 1-1

The full include-list for openPMD/openPMD-api/examples/7_extended_write_serial.cpp:
#include "openPMD/Dataset.hpp"             // for Dataset, Extent, Offset
#include "openPMD/Datatype.hpp"            // for determineDatatype, Datatype
#include "openPMD/IO/AccessType.hpp"       // for AccessType, AccessType::CR...
#include "openPMD/Iteration.hpp"           // for Iteration
#include "openPMD/Mesh.hpp"                // for Mesh
#include "openPMD/ParticlePatches.hpp"     // for ParticlePatches
#include "openPMD/ParticleSpecies.hpp"     // for ParticleSpecies
#include "openPMD/RecordComponent.hpp"     // for RecordComponent, RecordCom...
#include "openPMD/Series.hpp"              // for Series
#include "openPMD/backend/BaseRecord.hpp"  // for BaseRecord, UnitDimension
#include "openPMD/backend/Container.hpp"   // for Container<>::mapped_type
---
```

**Comment by anokfireball** [comment]
> clang's address sanitizer

Would be a very good idea, though we'll have to pay attention to our dependencies and the failures they introduce (e.g. #28).

> we want to add mappings

Very much agreed. Rather than for examples only, we should apply iwyu [pragmas](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md) across the internals of the API (most importantly ```openPMD.hpp```).

@ax3l What do you think about re-ordering the build stages such that the important stuff (namely unit tests) is run first to fail fast. Builds and stages that are allowed to fail (style, coverage) or only run a short period of time (style, static analysis), combined with ```fast_finish: true``` means that a CI build is valid once all tests pass that are not allowed to fail. If we put the other tests last, this would speed up our pipeline.

**Comment by ax3l** [comment]
> we should apply iwyu pragmas across the internals of the API (most importantly openPMD.hpp).

yes, `IWYU pragma: export` and including *all* headers inside `openPMD.hpp` should solve this

> re-ordering

ideally: fast (style, etc.) first as now and long-running last.

**Comment by ax3l** [comment]
That said, the current order *is already ok* as soon as caching kicks in. Please keep the order!

The reason why `iwyu` and `clang-tidy` are that slow is: they are not cached *yet*! (Caching needs at a successful, preceding build.) You could skip / comment them out until they are fixed.

**Pull request merged**
