### PR TITLE
Initial support for HDF5 subfiling

### PR DESCRIPTION
**Pull request by franzpoeschel**
I'm following the documentation in [this presentation](https://www.hdfgroup.org/wp-content/uploads/2022/09/HDF5-Subfiling-VFD.pdf).

TODO:

- [x] parameterization
- [x] opt-in
- [x] documentation

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Awesome, thank you!

**Comment by ax3l** [comment]
cc @guj and @jeanbez : just FYI, sub-filing support for HDF5 in openPMD-api now :)

**Comment by ax3l** [comment]
We should check if Conda-Forge (hdf5 and h5py), h5py (pip builds) and Spack enable this feature in the HDF5 package already (non-default).

**Comment by franzpoeschel** [comment]
Note that this needs to be enabled explicitly when configuring HDF5 `-DHDF5_ENABLE_SUBFILING_VFD=ON`.

**Comment by guj** [comment]
Is  MPI_THREAD_MULTIPLE. still a requirement to use subfiles for HDF5? 
If so, needs to state  in the doc.

**Comment by franzpoeschel** [comment]
> Is MPI_THREAD_MULTIPLE. still a requirement to use subfiles for HDF5? If so, needs to state in the doc.

Yes, it is a requirement. It's mentioned in the docs (`Note that the subfiling VFD needs to be enabled explicitly when configuring HDF5 and threaded MPI must be used.`), though the specific level is not mentioned yet (MPI_THREAD_MULTIPLE).

**Pull request merged**
