### PR TITLE
CD: Add Travis Architectures

### PR DESCRIPTION
**Pull request by ax3l**
Adds wheel builds for:
- ~~Linux aarch64~~: https://github.com/ornladios/ADIOS2/issues/2137
- ~~Linux ppc64le~~: https://github.com/pypa/auditwheel/issues/36 https://github.com/pypa/auditwheel/pull/213
- ~~Linux s390x~~: https://github.com/GTkorvo/dill/issues/15
- macOS 10.13 (XCode 9.4 ~2017)

https://docs.travis-ci.com/user/reference/osx/#using-macos

### CODE REVIEW

**Comment by chuckatkins** [comment]
While the error should probably be fixed I think it's safe to assume that s390x, i.e. IBM z series mainframe, is not a priority architecture for ADIOS.

**Comment by ax3l** [comment]
And `aarch64`? :)

**Comment by ax3l** [comment]
ADIOS1 compiles on s390x!!111 ;-)

**Comment by chuckatkins** [comment]
Aarch64 needs to be addressed, and I assume the issues are one in the same.  My point really though is that s390 specific issues though can be put on the back burner unless it's low hanging fruit.

**Comment by ax3l** [comment]
Fully agree, just looked like a low-hanging fruit to me to make the build for ADIOS2 more robust. For example, if `dill` does encounter an unknown architecture it should gracefully be disabled instead of failing the whole ADIOS2 build, I think.

**Comment by chuckatkins** [comment]
That's certainly the intent.  I likely just borked some of the logic back when I did the build system overhaul 2-3y ago.

**Pull request merged**
