### PR TITLE
Add all the performance-* clang-tidy checks

### PR DESCRIPTION
**Pull request by lucafedeli88**
This PR adds all the `performance-*` checks to `clang-tidy` CI test, namely:

- [performance-faster-string-find](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-faster-string-find.html)
- [performance-for-range-copy](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-for-range-copy.html)
- [performance-implicit-conversion-in-loop](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-implicit-conversion-in-loop.html)
- [performance-inefficient-algorithm](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-inefficient-algorithm.html)
- [performance-inefficient-string-concatenation](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-inefficient-string-concatenation.html)
- [performance-inefficient-vector-operation](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-inefficient-vector-operation.html)
- [performance-move-const-arg](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-move-const-arg.html)
- [performance-move-constructor-init](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-move-constructor-init.html)
- [performance-no-automatic-move](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-no-automatic-move.html)
- [performance-no-int-to-ptr](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-no-int-to-ptr.html)
- [performance-noexcept-move-constructor](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-noexcept-move-constructor.html)
- [performance-trivially-destructible](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-trivially-destructible.html)
- [performance-type-promotion-in-math-fn](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-type-promotion-in-math-fn.html)
- [performance-unnecessary-copy-initialization](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-unnecessary-copy-initialization.html)
- [performance-unnecessary-value-param](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-unnecessary-value-param.html)

### CODE REVIEW

**Comment by lucafedeli88** [comment]
I see that a test case is failing. I will investigate

**Comment by lucafedeli88** [comment]
> I see that a test case is failing. I will investigate

The bug should be fixed!

**Comment by franzpoeschel** [comment]
Currently looking through this. The checks are very useful, thank you for adding this!

It seems that in some places the suggested fixes by clang-tidy started an avalanche of recursive fixes and I'm trying to undo those. (Basic pattern: A `std::move()` was forgotten or wrongly applied, so clang-tidy suggests to use a `const &` argument and that change then propagates through the entire code base)

Feel free to ping either Axel or me when you need to have the CI started

**Comment by franzpoeschel** [comment]
I've taken the freedom to push a commit on this branch that reverts some of the changes and tries to fix the warnings in another way. Most of these were "pass by value" turned into "pass by reference" because of:

* `std::move` was forgotten or wrongly applied. Fix that instead of changing the function signatures.
* API consistency: Some parameters are needed only in some configurations. clang-tidy then thinks that an unused parameter should be turned to a reference. Depending on the `#ifdef` logic, several implementations may be chosen. Here, we should optimize for the implementations that actually use the parameters since the others are often just there to satisfy the linker.
* Planned changes: A parameter is not yet used today, but will be in future. clang-tidy again thinks that unused parameters should be references.

The one thing that is a bit dangerous about clang-tidy imo is that it is very eager to change the API and ABI because of an implementation detail. This is mostly fine since those cases can mostly be handled case-by-case, but one should be aware of it.

One method that seems to successfully trick clang-tidy is to define something like `template<typename T> void forget(T){}` and passing unused parameters off into that template. I'll need to add a second commit that puts this in its own header, but not today.

Let's first see what the CI now thinks of this.

EDIT: I seem to have broken some things. Will investigate next week.

**Comment by franzpoeschel** [comment]
Hey @lucafedeli88 
The CI is now passing. If you are fine with the changes I did (only in the code, I did not touch the checks), then I would merge this.

EDIT: I forgot one thing, CI needs to run again

**Review by franzpoeschel — APPROVED** [review]

**Comment by franzpoeschel** [comment]
Merging this now, thank you for adding this!
Since many files are affected, this is likely to cause merge conflicts. But since each single change is mostly rather simple, the single merge conflicts should not be hard to resolve. In doubt, current changes can be replaced by incoming changes, and then clang-tidy suggestions can be reapplied.

**Pull request merged**
