### PR TITLE
BP5 tests: Only run them if ADIOS2 has BP5

### LINKED ISSUE #1257: ADIOS BP5 Support: Conditional Compile Variant
Unfortunately, we cannot rely on ADIOS 2.8.0+ to provide BP5 unconditionally.

https://github.com/ornladios/ADIOS2/blob/v2.8.0/CMakeLists.txt#L155

We need to do more checks if that compile option was actually set.

X-ref: https://github.com/ornladios/ADIOS2/issues/3182

### PR DESCRIPTION
**Pull request by franzpoeschel**
Fix #1257

### CODE REVIEW

**Comment by ax3l** [comment]
Thanks a lot!

Do you also want to update the "bp5" locations in `src/IO/ADIOS/ADIOS2IOHandler.cpp`?

I also looked at `src/config.cpp` for `openPMD::getFileExtensions()` - but there we only list `bp` right now.

**Comment by franzpoeschel** [comment]
We don't currently check for available engines in the ADIOS2 backend at all (on Windows, there's no SST, but we don't check for that)
Maybe we should do it? But if so, then that should maybe go into a different PR. Currently, there will be an ADIOS2 error if selecting an unknown engine (e.g. "This version didnt compile with…" or "Unknown engine type …")



> I also looked at `src/config.cpp` for `openPMD::getFileExtensions()` - but there we only list `bp` right now.

Good point, this is a Todo for #1218

**Review by ax3l — APPROVED** [review]
Sounds good to me, thank you :)

**Comment by ax3l** [comment]
As discussed: BP5 patches will first land in 0.15.0

**Pull request merged**
