### PR TITLE
Travis: h5ls examples

### PR DESCRIPTION
**Pull request by ax3l**
Try to open the created examples with `h5ls`.

### CODE REVIEW

**Comment by ax3l** [comment]
@C0nsultant it looks like the early [`series.flush()`](https://github.com/openPMD/openPMD-api/blob/0.5.0-alpha/examples/3_write_serial.cpp#L66) ~~destroys~~ makes the `3_write_serial.h5` file unreadable :-o (commenting it out makes it readable again)

**Comment by anokfireball** [comment]
> `series.flush()` destroys the `3_write_serial.h5` file

Sorry, I can not reproduce locally. Example 3 works fine for me, wether with or without the *early* `Series::flush()`.

What do you mean by **destroy**?

**Comment by ax3l** [comment]
@C0nsultant sorry, updated the wording in the comment. If you run `h5ls -r` on your `3_write_serial.h5`, does it succeed? (Remove it first, run `ctest` again.)

**Comment by anokfireball** [comment]
> does it succeed

Yes. With a clean `samples` directory, `h5ls -r 3_write_serial.h5` works as expected:
```
/                        Group
/data                    Group
/data/1                  Group
/data/1/meshes           Group
/data/1/meshes/rho       Dataset {3, 3}
```

**Comment by ax3l** [comment]
Weird, not for me and the user I tried it with.
I can reproduce the problem in CI, just needs to run again (in progress).

**Comment by ax3l** [comment]
@C0nsultant ok, tests are coming in now. See the last line in Travis:
```bash
$ h5ls -r ../samples/3_write_serial.h5
../samples/3_write_serial.h5: unable to open file
```

(update: uh wait, that's the "file not fount" error... wrong path!)

**Comment by ax3l** [comment]
hm, maybe I am just very confused.

**Pull request closed without merging**
