### PR TITLE
MPark.Variant

### PR DESCRIPTION
**Pull request by ax3l**
Draft for removing `boost::variant` for a `std::variant` in from [MPark.Variant](https://github.com/mpark/variant) #70

### CODE REVIEW

**Review by anokfireball — APPROVED** [review]
While the dependency is still not nice to have, it's worth it for getting Boost out of the system earlier.

**Comment by ax3l** [comment]
rebased the draft to not use git submodules but the single-header version.

we can later on do exactly the same for replacing boost test with the single-header [catch2 library](https://github.com/catchorg/Catch2)

**Comment by anokfireball** [comment]
@ax3l TIL [Quantstack](https://github.com/QuantStack/xtl/blob/master/include/xtl/xvariant.hpp) uses this mpark::variant as well.

**Comment by ax3l** [comment]
Cool, didn't know that. Good sign :D

**Pull request merged**
