### PR TITLE
ADIOS: Fix Unused Parameters

### PR DESCRIPTION
**Pull request by ax3l**
Fix warnings in the ADIOS1 backend about unused parameters in unimplemented functionality.

### CODE REVIEW

**Review by anokfireball — APPROVED** [review]
[blind-review](https://github.com/zombie/blind-reviews "Review performed in blind mode")

**Comment by anokfireball** [comment]
I also introduced these [changes](https://github.com/openPMD/openPMD-api/pull/156/files#diff-1b6ee4cde139d7e493030d66fcca3217) in #156.

**Comment by ax3l** [comment]
Great, no prob!

Shall I fix them already and you rebase #156 against it or do you want to introduce it with #156 and we close this? (ideally I like small PRs that only change one thing at a time :) )

**Comment by anokfireball** [comment]
Smaller feature sets are definitely desirable for a smaller impact on the mental model.
I'll rebase against this change, there should not be a specific commit for this in #156, anyway.

**Pull request merged**
